[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

[target.x86_64-apple-darwin]
linker = "x86_64-apple-darwin-gcc"

[target.aarch64-apple-darwin]
linker = "aarch64-apple-darwin-gcc"
