name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 0

jobs:
  # Rust unit tests on Ubuntu
  rust-test-ubuntu:
    name: Rust Tests (Ubuntu)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Install std library
      run: chmod +x ./install_std.sh && ./install_std.sh
    - run: cargo test

  # Rust unit tests on Windows
  rust-test-windows:
    name: Rust Tests (Windows)
    runs-on: windows-2025
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Install std library
      run: .\install_std.sh
    - name: Run tests in release mode to avoid PDB issues
      run: cargo test --release

  # Python integration tests on Ubuntu
  python-test-ubuntu:
    name: Python Tests (Ubuntu)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Install std library
      run: chmod +x ./install_std.sh && ./install_std.sh
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Run Python tests
      run: |
        cd tests
        python run_tests.py --cicd

  # Python integration tests on Windows
  python-test-windows:
    name: Python Tests (Windows)
    runs-on: windows-2025
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Install std library
      run: .\install_std.sh
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Run Python tests (will build in release mode)
      run: |
        cd tests
        python run_tests.py --cicd
