name: Update and Deploy Issue Tracker

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          path: ./main-branch

      - name: Fetch historical data from gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: ./gh-pages
          continue-on-error: true

      - name: Prepare directory
        run: |
            cp main-branch/.github/scripts/track_issues.py .
            cp main-branch/.github/scripts/requirements.txt .
            cp -r main-branch/src .
            mkdir ./.issues/
            cp -r gh-pages/state ./.issues/state &2>/dev/null || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Generate Issue Report
        run: |
            python track_issues.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.issues
          publish_branch: gh-pages
          force_orphan: false
          commit_message: "docs: Update issue tracker report [skip ci]"
