name: Update and Deploy Issue Tracker

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: checkout main branch
        uses: actions/checkout@v4
        with:
          path: ./main-branch

      - name: fetch gh-pages branch for the historical data
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: ./gh-pages
          continue-on-error: true

      - name: generate new state and prepare for deploy
        run: |
            # copy the state from gh-pages branch into the main-branch checkout
            mkdir -p ./main-branch/.github/scripts/.issues/state
            cp -r gh-pages/state ./main-branch/.github/scripts/.issues/state &2>/dev/null || true

            cd main-branch/.github/scripts/

            pip install -r requirements.txt
            python track_issues.py

            popd

            cp -r ./main-branch/.github/scripts/.issues/ ./issues

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.issues
          publish_branch: gh-pages
          force_orphan: false
          commit_message: "docs: Update issue tracker report [skip ci]"
